incdir := $(srctree)/$(src)/include

incdir += lib/allocator/include
incdir += lib/arch/include
incdir += lib/attestation/include
incdir += lib/common/include
incdir += lib/debug/include
incdir += lib/gic/include
incdir += lib/mbedtls/include
incdir += lib/measurement/include
incdir += lib/qcbor/include
incdir += lib/realm/include
incdir += lib/rmm_el3_ifc/include
incdir += lib/smc/include
incdir += lib/s2tt/include
incdir += lib/t_cose/include
incdir += lib/timers/include
incdir += lib/xlat/include


obj-$(CONFIG_KVM) += entry.o handler.o